---
ship:
  MAX_SPEED: 10
  ACCELERATION: 2
  ROTATION_SPEED: 2.5 # rad/sec
  BREAKS: 7.5
  SIZE: 15 # window.height//SIZE
  controls:
    forward: 119 # 119 - A
    backward: 115 # 155 - S
    left: 100 # 100 - A
    right: 97 # 97 - D
    shoot: 32 # 32 - spacebar

WINDOW_SETTINGS:
  TICKSPEED: 60 # 60 Ticks per second
  WIDTH : 1920
  HEIGHT : 1080
  RESIZABLE: True
  FULLSCREEN: False
  MONITOR: 0
  STYLE: WINDOW_STYLE_DIALOG

LASER:
  LASER_SPEED: 30
  LASER_DELAY: 15